# Generated by Django 3.2.7 on 2021-09-20 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PressContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(max_length=50, verbose_name='label')),
                ('url', models.TextField(verbose_name='url')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_published')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
            ],
        ),
    ]
